name: Build and deliver to Docker Hub

on:
  push:
    branches: [master]


  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc1be24c3d234590a8db6e7dbf0a5b97 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_387507d6c75d4dbeb69eca168afb2db4 }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devices-service:latest
