name: Deploy Docker to Azure

on:
 push:
  branches:
    - master


jobs:
  deploy:
   runs-on: ubuntu-latest
   
   steps:
     - name: Deploy Docker to Azure Web App
       uses: azure/webapps-deploy@v2
       with: 
         app-name: 'devices-service'
         slot-name: 'production'
         publish-profile: ${{ secrets.AzureAppService_PublishProfile_a6e5632e5200468aa659e30d5bc94180 }}
         images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7fc0d6e8e9374667b73f96f5d1db6fda }}/milofow/devices-service:${{ github.sha }}'
