name: Docker Image CI and Deploy to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
      
      
  deploy:
   runs-on: ubuntu-latest
   steps:
   
    - name: Login to Azure
    - uses: azure/login@v1
      with: 
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
         
    - name: Deploy!
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create \
          -- name device-service
          --resource-group home-automation-dashboard
          --template-file target/devices-service-0.0.1-SNAPSHOT.jar

     
