# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - device-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc1be24c3d234590a8db6e7dbf0a5b97 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_387507d6c75d4dbeb69eca168afb2db4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bc1be24c3d234590a8db6e7dbf0a5b97 }}/milofow/devices-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'device-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8d59895ccd9943deb93915f95315dd9c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bc1be24c3d234590a8db6e7dbf0a5b97 }}/milofow/devices-service:${{ github.sha }}'